language: python
sudo: required

#python:
#- "3.7"

services:
- docker
- redis-server

before_install:
- sudo apt --yes --quiet update

# Use PostgreSQL 11
- sudo apt --yes --quiet autoremove --purge postgresql-{,client-,contrib-}{9,10}\*
- sudo apt --yes --quiet install postgresql-11 postgresql-client-11

# Install Docker
#- sudo apt --yes --quiet install docker-ce

# Install the pygobject build deps
#- sudo apt --yes --quiet install gobject-introspection libcairo2-dev libffi-dev libgirepository1.0-dev libglib2.0-dev

before_script:
# Create the PostgreSQL role and database
- sudo -u postgres createuser azafea
- sudo -u postgres createdb --owner=azafea azafea-tests

# Set the default passwords for PostgreSQL and Redis, as that's what the tests expect
- sudo -u postgres psql --command="ALTER USER azafea WITH PASSWORD 'CHANGE ME!!';"
- redis-cli config set requirepass 'CHANGE ME!!'

# Build the Docker image
- docker build --build-arg build_type=dev --tag "azafea:tests" .

matrix:
  include:
  - name: "Integration Tests"
    script:
    - docker run --rm --network=host --entrypoint="" "azafea:tests" pipenv run test-all
  - name: "Lint and Type Checking"
    script:
    - docker run --rm --network=host --entrypoint="" "azafea:tests" pipenv run lint
