dist: bionic
sudo: required
language: minimal

branches:
  only:
  - master

services:
- docker

install:
- docker build --build-arg build_type=dev --tag azafea-tests .

before_script:
- docker run -d --name=redis --network=host redis:5-alpine --requirepass 'CHANGE ME!!'
- docker run -d --name=postgres --network=host -e 'POSTGRES_PASSWORD=CHANGE ME!!' -e 'POSTGRES_USER=azafea' -e 'POSTGRES_DB=azafea-tests' postgres:11-alpine

after_script:
- docker rm -f redis postgres

matrix:
  include:
  - name: "Integration Tests"
    script:
    - docker run --rm --network=host --entrypoint="" azafea-tests pipenv run test-all
  - name: "Lint and Type Checking"
    script:
    - docker run --rm --network=host --entrypoint="" azafea-tests pipenv run lint
