language: python
sudo: required

branches:
  only:
  - master

python:
- "3.7"

services:
- redis-server

before_install:
- sudo apt --yes --quiet update
- sudo apt --yes --quiet autoremove --purge postgresql-{,client-,contrib-}{9,10}\*
- sudo apt --yes --quiet install postgresql-11 postgresql-client-11

install:
- pipenv install --dev

before_script:
# Create the PostgreSQL role and database
- sudo -u postgres createuser azafea
- sudo -u postgres createdb --owner=azafea azafea-tests

# Set the default passwords for PostgreSQL and Redis, as that's what the tests expect
- sudo -u postgres psql --command="ALTER USER azafea WITH PASSWORD 'CHANGE ME!!';"
- redis-cli config set requirepass 'CHANGE ME!!'

matrix:
  include:
  - name: "Integration Tests"
    script:
    - pipenv run test-all
  - name: "Lint and Type Checking"
    script:
    - pipenv run lint
